# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/nodelogin
#     username: root
#     password: @pple!1234
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#     show-sql: true